Build and upload release asset on tag
aeternity/rebar3 pull request #7
Opened 2019-05-16 11:22 UTC by valerifilipov

2019-05-16 12:42 UTC, dincho commented on .circleci/config.yml
> +  build_push:
Perhaps you meant build_publish ?

2019-05-16 12:43 UTC, dincho requested changes
Use `ae-library` context for gh token

2019-05-17 11:35 UTC, dincho approved these changes

2019-05-27 11:37 UTC, sennui approved these changes

2019-05-27 11:39 UTC, velzevur approved these changes

2019-05-27 11:45 UTC, merged